export interface ILegacyPageContext {
    alertsEnabled: boolean;
    allowSilverlightPrompt: string;
    clientServerTimeDelta: any;
    crossDomainPhotosEnabled: boolean;
    currentCultureName: string;
    currentLanguage: number;
    currentUICultureName: string;
    customMarkupInCalculatedFieldDisabled: boolean;
    isAppWeb: boolean;
    isSiteAdmin: boolean;
    layoutsUrl: string;
    pageItemId: number;
    pageListId: any;
    pagePersonalizationScope: number;
    serverRequestPath: string;
    siteAbsoluteUrl: string;
    siteClientTag: string;
    siteServerRelativeUrl: string;
    systemUserKey: string;
    tenantAppVersion: string
    updateFormDigestPageLoaded: any;
    userId: any;
    userLoginName: string;
    webAbsoluteUrl: string;
    webLanguage: number;
    webLogoUrl: string;
    webPermMasks: any;
    webServerRelativeUrl: string;
    webTemplate: any;
    webTitle: string;
    webUIVersion: any;
}