export var LIST_PAGED_LIMIT = 4999;
export var FIELD_TYPE_USER = "SP.FieldUser";
export var FIELD_TYPE_LOOKUP = "SP.FieldLookup";
export var FIELD_TYPE_ATTACHMENT = "SP.Field";
/*Styles*/
// export const CSS_BOOTSTRAP = "/SiteAssets/vendor/bootstrap-4.3.1/css/bootstrap.min.css";
export var CSS_FONTS = "/SiteAssets/css/fonts.css";
export var CSS_DATATABLE = "/SiteAssets/css/jquery.dataTables.min.css";
export var CSS_STYLE = "/SiteAssets/css/style.css";
export var CSS_BOOTSTRAP = "/SiteAssets/css/bootstrap.min.css";
export var CSS_MATERIALDESIGNICONS = "/SiteAssets/vendors/mdi/css/materialdesignicons.min.css";
export var CSS_FONTAWESOME = "/SiteAssets/css/font-awesome.min.css";
export var CSS_FONTAWESOMEALL = "/SiteAssets/css/all.css";
export var CSS_CUSTOM = "/SiteAssets/css/custom.css";
export var CSS_JQUERYUI = "/SiteAssets/css/jquery-ui.css";
export var CSS_SUMMERNOTE = "/SiteAssets/css/summernote-bs4.css";
// export const CSS_TREEVIEW = "/SiteAssets/css/bootstrap-treeview.css";
// export const CSS_FONTAWESOME5 = "/SiteAssets/css/all.css";
/*Js*/
export var JS_JQUERY = "/SiteAssets/js/jquery.min.js";
export var JS_BOOTSTRAP = "/SiteAssets/js/bootstrap.min.js";
export var JS_BOOTSTRAPBUNDLE = "/SiteAssets/js/bootstrap.bundle.min.js";
export var JS_JQUERYUI = "/SiteAssets/js/jquery-ui.js";
export var JS_OFFCANVAS = "/SiteAssets/js/off-canvas.js";
export var JS_HOVERABLECOLLAPSE = "/SiteAssets/js/hoverable-collapse.js";
export var JS_MISC = "/SiteAssets/js/misc.js";
export var JS_DATATABLE = "/SiteAssets/js/jquery.dataTables.min.js";
export var JS_FONTAWESOME = "/SiteAssets/js/fontawesome.min.js";
//# sourceMappingURL=constants.js.map