export var ListTemplateType;
(function (ListTemplateType) {
    ListTemplateType[ListTemplateType["CustomList"] = 100] = "CustomList";
    ListTemplateType[ListTemplateType["DocumentLibrary"] = 101] = "DocumentLibrary";
    ListTemplateType[ListTemplateType["Survey"] = 102] = "Survey";
    ListTemplateType[ListTemplateType["Links"] = 103] = "Links";
    ListTemplateType[ListTemplateType["Announcements"] = 104] = "Announcements";
    ListTemplateType[ListTemplateType["Contacts"] = 105] = "Contacts";
    ListTemplateType[ListTemplateType["Calendar"] = 106] = "Calendar";
    ListTemplateType[ListTemplateType["Tasks"] = 107] = "Tasks";
    ListTemplateType[ListTemplateType["DiscussionBoard"] = 108] = "DiscussionBoard";
    ListTemplateType[ListTemplateType["PictureLibrary"] = 109] = "PictureLibrary";
    ListTemplateType[ListTemplateType["DataSources"] = 110] = "DataSources";
    ListTemplateType[ListTemplateType["FormLibrary"] = 115] = "FormLibrary";
    ListTemplateType[ListTemplateType["NoCodeWorkflows"] = 117] = "NoCodeWorkflows";
    ListTemplateType[ListTemplateType["CustomWorkflowProcess"] = 118] = "CustomWorkflowProcess";
    ListTemplateType[ListTemplateType["WikiPageLibrary"] = 119] = "WikiPageLibrary";
    ListTemplateType[ListTemplateType["CustomGrid"] = 120] = "CustomGrid";
    ListTemplateType[ListTemplateType["NoCodePublicWorkflows"] = 122] = "NoCodePublicWorkflows";
    ListTemplateType[ListTemplateType["WorkflowHistory"] = 140] = "WorkflowHistory";
    ListTemplateType[ListTemplateType["ProjectTasks"] = 150] = "ProjectTasks";
    ListTemplateType[ListTemplateType["PublicWorkflowsExternalList"] = 600] = "PublicWorkflowsExternalList";
    ListTemplateType[ListTemplateType["IssuesTracking"] = 1100] = "IssuesTracking";
})(ListTemplateType || (ListTemplateType = {}));
export var TemplateFileType;
(function (TemplateFileType) {
    TemplateFileType[TemplateFileType["StandardPage"] = 0] = "StandardPage";
    TemplateFileType[TemplateFileType["WikiPage"] = 1] = "WikiPage";
    TemplateFileType[TemplateFileType["FormPage"] = 2] = "FormPage";
    TemplateFileType[TemplateFileType["ClientSidePage"] = 3] = "ClientSidePage";
})(TemplateFileType || (TemplateFileType = {}));
export var FieldTypeKind;
(function (FieldTypeKind) {
    FieldTypeKind[FieldTypeKind["Invalid"] = 0] = "Invalid";
    FieldTypeKind[FieldTypeKind["Integer"] = 1] = "Integer";
    FieldTypeKind[FieldTypeKind["Text"] = 2] = "Text";
    FieldTypeKind[FieldTypeKind["Note"] = 3] = "Note";
    FieldTypeKind[FieldTypeKind["DateTime"] = 4] = "DateTime";
    FieldTypeKind[FieldTypeKind["Counter"] = 5] = "Counter";
    FieldTypeKind[FieldTypeKind["Choice"] = 6] = "Choice";
    FieldTypeKind[FieldTypeKind["Lookup"] = 7] = "Lookup";
    FieldTypeKind[FieldTypeKind["Boolean"] = 8] = "Boolean";
    FieldTypeKind[FieldTypeKind["Number"] = 9] = "Number";
    FieldTypeKind[FieldTypeKind["Currency"] = 10] = "Currency";
    FieldTypeKind[FieldTypeKind["URL"] = 11] = "URL";
    FieldTypeKind[FieldTypeKind["Computed"] = 12] = "Computed";
    FieldTypeKind[FieldTypeKind["Threading"] = 13] = "Threading";
    FieldTypeKind[FieldTypeKind["Guid"] = 14] = "Guid";
    FieldTypeKind[FieldTypeKind["MultiChoice"] = 15] = "MultiChoice";
    FieldTypeKind[FieldTypeKind["GridChoice"] = 16] = "GridChoice";
    FieldTypeKind[FieldTypeKind["Calculated"] = 17] = "Calculated";
    FieldTypeKind[FieldTypeKind["File"] = 18] = "File";
    FieldTypeKind[FieldTypeKind["Attachments"] = 19] = "Attachments";
    FieldTypeKind[FieldTypeKind["User"] = 20] = "User";
    FieldTypeKind[FieldTypeKind["Recurrence"] = 21] = "Recurrence";
    FieldTypeKind[FieldTypeKind["CrossProjectLink"] = 22] = "CrossProjectLink";
    FieldTypeKind[FieldTypeKind["ModStat"] = 23] = "ModStat";
    FieldTypeKind[FieldTypeKind["Error"] = 24] = "Error";
    FieldTypeKind[FieldTypeKind["ContentTypeId"] = 25] = "ContentTypeId";
    FieldTypeKind[FieldTypeKind["PageSeparator"] = 26] = "PageSeparator";
    FieldTypeKind[FieldTypeKind["ThreadIndex"] = 27] = "ThreadIndex";
    FieldTypeKind[FieldTypeKind["WorkflowStatus"] = 28] = "WorkflowStatus";
    FieldTypeKind[FieldTypeKind["AllDayEvent"] = 29] = "AllDayEvent";
    FieldTypeKind[FieldTypeKind["WorkflowEventType"] = 30] = "WorkflowEventType";
    FieldTypeKind[FieldTypeKind["MaxItems"] = 31] = "MaxItems"; //Must not be used. The value = 31.
})(FieldTypeKind || (FieldTypeKind = {}));
export var CalendarEventPeriod;
(function (CalendarEventPeriod) {
    CalendarEventPeriod[CalendarEventPeriod["Today"] = 0] = "Today";
    CalendarEventPeriod[CalendarEventPeriod["Month"] = 1] = "Month";
    CalendarEventPeriod[CalendarEventPeriod["Year"] = 2] = "Year";
})(CalendarEventPeriod || (CalendarEventPeriod = {}));
export var Status;
(function (Status) {
    Status["Draft"] = "Draft";
    Status["Approver1"] = "Pending with Approver 1";
    Status["Approver2"] = "Pending with Approver 2";
    Status["Approver3"] = "Pending with Approver 3";
    Status["Approver4"] = "Pending with Approver 4";
    Status["Approver5"] = "Pending with Approver 5";
    Status["Rejected"] = "Rejected";
    Status["Approved"] = "Approved";
    Status["Cancelled"] = "Cancelled";
    Status["Resubmission"] = "Pending for Resubmission";
})(Status || (Status = {}));
export var Action;
(function (Action) {
    Action["Submitted"] = "Submitted";
    Action["Approved"] = "Approved";
    Action["RequestedforAmendment"] = "Requested for Amendment";
    Action["Delegated"] = "Delegated";
    Action["Approver4"] = "Pending with Approver 4";
    Action["Approver5"] = "Pending with Approver 5";
    Action["Rejected"] = "Rejected";
    Action["Cancelled"] = "Cancelled";
    Action["Resubmitted"] = "Resubmitted";
    Action["Delegation"] = "Delegation";
})(Action || (Action = {}));
export var UrlTabs;
(function (UrlTabs) {
    UrlTabs["Draft"] = "Draft";
    UrlTabs["MyRequests"] = "MyRequests";
    UrlTabs["Resubmissions"] = "Resubmissions";
    UrlTabs["ActionedRequests"] = "ActionedRequests";
    UrlTabs["AllRequests"] = "AllRequests";
})(UrlTabs || (UrlTabs = {}));
//# sourceMappingURL=enums.js.map