import * as React from 'react';
import './TeamTimesheet.module.scss';
import { ITeamTimesheetProps } from './ITeamTimesheetProps';
import "select2/dist/css/select2.min.css";
import "select2/dist/js/select2.min.js";
import 'jquery-ui-dist/jquery-ui.min.js';
import 'jquery-ui-dist/jquery-ui.min.css';
export interface ITeamTimesheetState {
    TeamListData: any[];
    groupName: string;
    ProjectList: any[];
    project: any;
    dateRange: any;
    fromDate: any;
    toDate: any;
    errorMessageFromDate: string;
    errorMessageToDate: string;
    PeopleId: any;
    TaskType: any[];
    status: string;
    statusFilter: string;
    successMessage: string;
    alertMessage: string;
    screen: boolean;
    isPending: boolean;
    groupColumn: any;
    isAdmin: boolean;
    isHR: boolean;
    event: any;
    staff: any[];
    allUser: any[];
    userMail: any;
}
export default class TeamTimesheet extends React.Component<ITeamTimesheetProps, ITeamTimesheetState> {
    private _spservice;
    protected ppl: any;
    constructor(props: any);
    private pickerStylesSingle;
    componentDidMount: () => Promise<void>;
    private loadDefaultDates;
    private handleHamBurger;
    private checkPermission;
    private getTaskType;
    private getProjects;
    private getAllUser;
    private getManager;
    private getStaff;
    private getPendingTimesheets;
    private getAllTimesheets;
    private getTeamListData;
    private handleExcel;
    private callDataTable;
    private hideSearch;
    private showSearch;
    private getPeople;
    private handleSelectedId;
    private handleDateRange;
    private handleFromDateChange;
    private handleToDateChange;
    private handleStatus;
    private handleGroupBy;
    private handleSearch;
    private handleClear;
    private getItemlist;
    private handleApprove;
    private handleReject;
    private handleRevise;
    private calendar;
    handleMouseEnter: (info: any) => void;
    private calcTotalEfforts;
    private calcTotalAllEfforts;
    private calcEfforts;
    private toggleLoader;
    render(): React.ReactElement<ITeamTimesheetProps>;
}
//# sourceMappingURL=TeamTimesheet.d.ts.map