import * as React from 'react';
import './MyTimesheet.module.scss';
import { IMyTimesheetProps } from './IMyTimesheetProps';
import "select2/dist/css/select2.min.css";
import "select2/dist/js/select2.min.js";
import 'jquery-ui-dist/jquery-ui.min.js';
import 'jquery-ui-dist/jquery-ui.min.css';
export interface IMyTimesheetState {
    EmployeeList: any[];
    ProjectList: any[];
    project: any;
    dateRange: any;
    fromDate: any;
    toDate: any;
    errorMessageFromDate: string;
    errorMessageToDate: string;
    TaskType: any[];
    status: string;
    statusFilter: string;
    successMessage: string;
    alertMessage: string;
    screen: boolean;
    export: boolean;
    isPending: boolean;
    isCalender: boolean;
    efforts: any;
    isManager: boolean;
    createdBy: any;
    groupColumn: any;
    weekendsVisible: true;
    currentEvents: [];
    event: any;
    ManagerEMail: any;
    ManagerTitle: any;
}
export default class MyTimesheet extends React.Component<IMyTimesheetProps, IMyTimesheetState> {
    private _spservice;
    constructor(props: any);
    componentDidMount(): Promise<void>;
    private loadDefaultDates;
    private handleHamBurger;
    private getManager;
    private getProjects;
    private getTaskType;
    private getAllTimesheets;
    private getPendingTimesheets;
    private handleExcel;
    private callDataTable;
    private hideSearch;
    private showSearch;
    private handleSelectedId;
    private handleDateRange;
    private handleFromDateChange;
    private handleToDateChange;
    private handleStatus;
    private handleGroupBy;
    private handleSearch;
    private handleClear;
    private handleNewTimesheet;
    private handleSubmit;
    private getItemlist;
    private handleUpdate;
    private handleResubmit;
    private handleDelete;
    handleMail: () => void;
    private handleInput;
    private handleClose;
    private calcTotalEfforts;
    private calcTotalAllEfforts;
    private calcEfforts;
    private toggleLoader;
    private calendar;
    convertToPlain(html: any): string;
    handleMouseEnter: (info: any) => void;
    renderEventContent(eventInfo: any): JSX.Element;
    renderSidebarEvent(event: any): JSX.Element;
    handleWeekendsToggle: () => void;
    handleDateSelect: (selectInfo: any) => void;
    handleEventClick: (clickInfo: any) => void;
    handleEvents: (events: any) => void;
    render(): React.ReactElement<IMyTimesheetProps>;
}
//# sourceMappingURL=MyTimesheet.d.ts.map